### ISSUE TITLE
Add items in Inventory Is not working.

### ISSUE THREAD

**Issue by HotShot0** [colecrouter/stardew-save-editor#11]
Whenever i add any items in inventory it display as weeds in game.

**Comment by a-rabin** [comment]
same here.

**Comment by colecrouter** [comment]
Fixed via be733ff6edd470d684d4e33451e0d4ecec24f391. Please share any items you find that are still not working.

**Comment by k1rafps** [comment]
I believe that Prismatic Shard is one of the items that still don't function, as well as Staircases.
