### ISSUE TITLE
Farmhands editing doesnt seem to be implamented

### ISSUE THREAD

**Issue by AidanTheBandit** [colecrouter/stardew-save-editor#12]
It would be cool to edit farmhands like you can with players. Trying to edit it by hand seems to break the file though

**Comment by colecrouter** [comment]
Hello @AidanTheBandit,

Originally, you could switch between player & farmhands using these buttons:
![image](https://github.com/colecrouter/stardew-save-editor/assets/15883173/0985cdc8-d246-45d4-9b65-118697934727)
I don't have a 1.6 save w/ multiple players ATM, so I can't verify if this does/doesn't work. Would you be able to confirm?

**Comment by maxpowa** [comment]
@colecrouter, I can confirm that with 1.6 local co-op savegame, these buttons do nothing.

**Comment by colecrouter** [comment]
Thanks for the tip @maxpowa.

I've gone ahead and patched it. Let me know if you run into further issues.
