### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by JulesMcGrules** [colecrouter/stardew-save-editor#13]
For some reason whenever i use this item editor it no longer works. The game freezes on the loading screen of the world then crashes.

**Comment by colecrouter** [comment]
Hello. Does this happen after making any particular changes (such as adding a specific item)?

You can test by uploading then downloading your save, and seeing if it works. If not, it's likely due to a change in 1.6.

**Comment by JulesMcGrules** [comment]
i worked a few days ago

**Comment by JulesMcGrules** [comment]
oh yeah it must be an item

**Comment by JulesMcGrules** [comment]
Confirmed it is the witch hat DON'T use it.

**Comment by colecrouter** [comment]
@JulesMcGrules can you try again and confirm if the issue still exists.

**Comment by JulesMcGrules** [comment]
most of the time you can't get items that you have not unlocked yet in the ga,e
