### ISSUE TITLE
[Feature Request] Multiplayer Save Host Switcher

### ISSUE THREAD

**Issue by RhanCandia** [colecrouter/stardew-save-editor#19]
Hi there. I noticed you have the “Switch Characters” feature. I am not sure if that’s what I need. 

But can you add a feature that would allow me to change the host character on w multiplayer save file?

**Comment by colecrouter** [comment]
Currently, switching host & farmhands isn't supported, but it could be added in the future.

For now, you can try [a solution like this](https://www.youtube.com/watch?v=nzcv-ei4yT8) if you haven't already.
