### ISSUE TITLE
Tabs character, crafting and cooking don't seem to work

### ISSUE THREAD

**Issue by D0V4HKIIN** [colecrouter/stardew-save-editor#22]
I edited a save and the tabs character, crafting and cooking did not do anything. Also when you change something in one of those tabs, leave it and come back the changes disappeared.

**Comment by colecrouter** [comment]
Thanks, I was able to fix the character tab issue. However, I wasn't able to confirm the issue with the crafting or cooking tabs. We've had a couple people confirm that was working, somewhat recently.

Would you mind sharing if there were any steps in particular you had done to encounter this?

**Comment by D0V4HKIIN** [comment]
my game crashes when changing the skills in the character menu :(. (i did change a lot bunch of stuff so might have been too much)

For the crafting and cooking tab, the issue is still there. It's really simple:
load save
go to crafting tab
select something
go to other tab
go back to crafting tab
notice that the previously selected craft is not selected anymore.

(I actually don't know how to cook in the game yet so can't really test that lol. I am just trying to replicate as closely as possible to a save i have om my switch)

Here is my savefile if you want to experiment with it.
[Crypto_385580149.zip](https://github.com/user-attachments/files/16984189/Crypto_385580149.zip)

**Comment by D0V4HKIIN** [comment]
For the character skills, changing farming from lvl 0 to lvl 5 made the game crash but changing from 0 to 4 didn't change anything in game D:

**Comment by colecrouter** [comment]
The skill tab should be working now.

I wasn't able to recreate the crafting issue, even with your save file. I dug around for a few weeks, but found no leads. I did some major library updates, maybe that will have resolved the problem. If you can, please try again and post back.

**Comment by colecrouter** [comment]
Closing as stale. Please reopen if the issue persists.
