### ISSUE TITLE
Cannot edit weapon stat

### ISSUE THREAD

**Issue by Tetrabiblos013** [colecrouter/stardew-save-editor#26]
The inventory always gone after edit my weapon stat
And also i can't save it pls help
![Screenshot (450)](https://github.com/user-attachments/assets/8427436d-f708-4e12-9fd5-17362c64a2e8)

**Comment by colecrouter** [comment]
Could you provide some detail into what exactly stat you changed, and which weapon it was? I'm trying to do the same thing, but I'm not running into any problems.

Also, you can share your save file here. You can also press F12, and share any errors in the console

**Comment by Tetrabiblos013** [comment]
I tried to edit the crit chance of my galaxy sword and dragontooth hammer, but after i tried to save it was like freezing

Tried to remove all of my mod but it still doesn't work
[Harmonia_381995580.zip](https://github.com/user-attachments/files/17632563/Harmonia_381995580.zip)

**Comment by colecrouter** [comment]
Thanks for the info. I tried doing as you describe, but I wasn't able to recreate it. Maybe there's something specific in your save triggering it.

It looks like the file you uploaded is corrupt or invalid, could you try uploading it again?

**Comment by Tetrabiblos013** [comment]
It's working right now, I move the save file first from Appdata folder before edit it lol
