### ISSUE TITLE
Can't download file

### ISSUE THREAD

**Issue by Andersans11** [colecrouter/stardew-save-editor#27]
When pressing the "Save" button, nothing happens, and the inventory screen disappears if it is clicked off and on again.

**Comment by hewasajumperboy** [comment]
I've seen the same error.  I don't have experience debugging web apps but I can add some color here.  

On downloading, Firefox console gives me:
`Uncaught (in promise) Error: Failed to generate XML
    Immutable 6
        export
        download
        h
        onclick
        __click
        D
SaveFile.svelte.BB8dlH03.js:2:8709
`

Which appears to map to [this line](https://github.com/colecrouter/stardew-save-editor/blob/24fcb841dd6dec5d5bc7bbd104d356547cfe304a/src/lib/SaveFile.svelte.ts#L136) in SaveFile.svelte.ts.  There was a change to the XML creation above this line 4 days ago, which I assume might be failing in the json/XML build routine above this line, but this I'm quickly getting out of my depth here.

Before the latest commit it would fail to download on creating certain items.  After the latest commit, it fails to download even unmodified, vanilla saves from newly created games.

**Comment by colecrouter** [comment]
Thanks for the insight @hewasajumperboy. Looks like there was a silly mistake during the refactor from Svelte 4 to 5, and the save files were being exported with a missing XML tag. I'm going to bring back a test for that later. Let me know if you still encounter this issue.
