### ISSUE TITLE
Some items cannot be displayed and modified normally.

### ISSUE THREAD

**Issue by REnLinuxx** [colecrouter/stardew-save-editor#28]
Take an example：
Dried Melon cannot be displayed normally. Select the corresponding position of "Dried Melon" to display the name of the item, but without its pattern, and the quantity cannot be modified.

![Screenshot_2024-11-09-12-36-22-875_com android chrome-edit](https://github.com/user-attachments/assets/611e94c5-c8c8-43bf-a0fb-618a59e9e805)

**Comment by colecrouter** [comment]
Sorry, I'm not familiar with a "Dried Melon" item? I can only see "Dried Fruit" and "Dried Mushrooms". Am I mistaken?

**Comment by REnLinuxx** [comment]
Do you need me to give you the corresponding screenshots after entering the game, so that you can judge the situation?
