### ISSUE TITLE
How do I install?

### ISSUE THREAD

**Issue by Lucky6509** [colecrouter/stardew-save-editor#29]
How do I add my save when I edited the save it downloaded something called todo.phps what do I do with that?

**Comment by colecrouter** [comment]
Hi,

It's meant to replace the file you uploaded. If your original file was name `MyFarm_123456789`, that's what you would name it. You would then need to put it back into the same `%appdata%\StardewValley\Saves\MyFarm_123456789` folder (for example).

I've pushed a change, so when you download the file, it suggests the original file name. Hopefully that makes it clearer.
