### ISSUE TITLE
Save won't show

### ISSUE THREAD

**Issue by Lucky6509** [colecrouter/stardew-save-editor#30]
**Describe the changes you made**
- added money

**Additional context**
I just added some money in my save and when I opened Stardew valley it didn't show my save. I am using the latest version of Stardew valley android version 1.6.13.2

**Comment by colecrouter** [comment]
Hi, I just tried on version 1.6.14 and I had no issues.

It's not common for the save to not show up at all. If that happens, it usually means that either your save file isn't named correctly, or your SaveGameInfo is missing.

Your folders should look something like this:
```
com.chucklefish.stardewvalley/
└── files/
    └── Saves/
        └── Farm_340137149/
            ├── Farm_340137149
            └── SaveGameInfo
```

If you don't find any luck, feel free to upload it here.  I can try it on my own device.

**Comment by colecrouter** [comment]
It should support Android; as far as I know, both use the same file format (I used to sync my PC & Android saves during 1.5). If you're willing to upload one of those saves, I can try on my own phone and see if I have the same issue.

I also know there were some bugs in the more recent SDV updates, so maybe you're on 1.6.14 or whatever the latest version is currently.
