### ISSUE TITLE
Website 404 error

### ISSUE THREAD

**Issue by HaruhinoStar** [colecrouter/stardew-save-editor#32]
After selecting the archive file, the website 404 did not respond
![IMG_20241114_134730](https://github.com/user-attachments/assets/ab847e44-edf6-4adc-9ccd-2b87a70681e8)

**Comment by HaruhinoStar** [comment]
the website 404 did not respond

**Comment by colecrouter** [comment]
Thanks, should be fixed now. You might need to clear cache.
