### ISSUE TITLE
How do you add items

### ISSUE THREAD

**Issue by zaldhyx77** [colecrouter/stardew-save-editor#33]
how do you add item exactly? i tried to click on empty slot in my back, select the items i want from the list, then what? theres no add button just trash icon...
![Uploading Screenshot_315.png…]()

**Comment by zaldhyx77** [comment]
![Screenshot_315](https://github.com/user-attachments/assets/c8c42231-9fb4-40b6-815a-cbc4a5a678a4)

**Comment by colecrouter** [comment]
There was an effect loop preventing the new items from being added to the inventory. Should be fixed as of 89919057c668aa907dddf60177c16ea6e398c88a Post back if the issue persists, thanks.
