### ISSUE TITLE
Fishing Level Resets to Level 1

### ISSUE THREAD

**Issue by oddGo** [colecrouter/stardew-save-editor#34]
Hi!

Upon loading my save, I noticed that for some reason, the editor moved all of my experience from the Fishing Skill into the Mining Skill, which was very strange. I tried to manually fix it by changing the experience levels of both to what they should be. After doing this though, I loaded my save (no issues with load) and found that the moment I earned any amount of fishing experience, my level would change from Level 6 back to Level 1. 

The in-game UI shows that until I earn fishing xp, I am still considered Fishing Level 6, and my bar when attempting to catch something reflects that. But the UI updates to Fishing Level 1 the moment I catch something, as mentioned.

**Comment by colecrouter** [comment]
Interesting. I set my XP as follows:
![image](https://github.com/user-attachments/assets/7c20ad99-6337-4eec-bd04-4959f8d2b348)
And this is what skills updated in-game:
![image](https://github.com/user-attachments/assets/95e63118-2707-4725-9692-ee7d2439f353)
Looks like the save file values for mining and fishing are swapped vs how they show up in game. Who would've known? Thanks for finding this.

**Comment by colecrouter** [comment]
> After doing this though, I loaded my save (no issues with load) and found that the moment I earned any amount of fishing experience, my level would change from Level 6 back to Level 1.

Most likely, this has something to do with levels vs. xp. They get stored separately, so it's likely that the game does some correction when one is updated without the other. I could be wrong; post back if the issues persists.
