### ISSUE TITLE
Character doesn't look like it should after saving (1.6.14)

### ISSUE THREAD

**Issue by sbb13** [colecrouter/stardew-save-editor#35]
After editing my save, the character looks very wierd. The first image is in the save editor and the second is in game.
![Screenshot_20241115_195118](https://github.com/user-attachments/assets/a2a0c627-d9e5-4cf2-a0c0-14a77d16d959)
![Screenshot_20241115_195215](https://github.com/user-attachments/assets/d7bf804d-0904-40f3-9bc5-78a59d74c28a)

**Comment by colecrouter** [comment]
@sbb13 could you clarify; which picture is correct? Is it that *after* editing your save, the character no longer looks correct? Or is the preview on the website wrong? What did you change about your character on the website?

**Comment by sbb13** [comment]
The first one should be correct. Changing the character appearance in the save editor leads me to the second image. Nothing else seems to do this. This is after editing my save. Right now I reverted my save to a previous state, one that was made before editing the appearance in the save editor to bring the correct appearance.

**Comment by colecrouter** [comment]
Thanks for the info. I just uploaded a character, and changed the eye color, accessory, and skin tone, but it showed up as expected in-game.

Would you be willing to share your "working" save file? Also, could you tell me which settings you tried to change in the appearance tab (maybe one of them is bugged). Thanks again.

**Comment by sbb13** [comment]
Ok!
This character was made in vanilla, but got some mods added. The issue persists into vanilla, though.
https://drive.google.com/drive/folders/1QZMO-spfHi5QQQB4Nz9urAszebPrgkRU?usp=sharing
I was able to recreate the error with changing eye and facial hair color. I dont know if just one produces the error or both.
If it is important, I am on Fedora Linux 41 with Steam installed through flatpak.

**Comment by colecrouter** [comment]
Alright, I was able to find the problem. Looks like some values were being convert into a transparent color. It should be good to go now 👍
