### ISSUE TITLE
Save Edit Ps4 version

### ISSUE THREAD

**Issue by CostelaCNX** [colecrouter/stardew-save-editor#37]
Hi there, is possible to make a compatibility to ps4 save game? I have one extracted file if need for study. 

Tks in advice

**Comment by colecrouter** [comment]
Hi, I was under the impression that the saves for SDV were the same across all platforms (except for NSW). I've been transferring saves across Android/iOS/Windows/macOS/Linux with no problems.

I found [this Reddit post](https://www.reddit.com/r/StardewValley/comments/1cq8kmq/transferring_ps4_saves_to_pc_tutorial/) so I'd imagine it's not much different, but I could be wrong. If this is the case, I'd happy to take look, but I can't make any promises myself.

If the above method *does* work, then I would be more than happy to include some instructions for console players.

**Comment by colecrouter** [comment]
Closing in lieu of #39, PS4 saves are confirmed to work. I plan to add some full instructions in the future.
