### ISSUE TITLE
PS4 Save Help

### ISSUE THREAD

**Issue by SirTribby** [colecrouter/stardew-save-editor#39]
Hi! First and foremost thank you for this godsend of an editor! You have no idea how much it's helped! So just a quick question, so unlike the last person who recently had PS4 save issues, I do not have those issues. With Save Wizard and Extracting the RAW file I can drag and drop directly into your editor and works flawlessly! My issue actually stems from me trying to get my PS4 save into the Farm Foundry editor cause it has options I really love like being able to edit specific chests on my farm and fill them with whatever items I need. And Farm Foundry doesn't load PS4 saves at the moment cause its just broken so I had been using your website to actually just drag and drop my save and then save immediately and that newly created file would load into Farm Foundry and I was able to open that file in notepad and copy the contents of the txt into advanced mode on save wizard and it would actually work! However I went to try today and it's not working unfortunately and I have done about every counter measure to try to no avail. So my question really is, is have you done anything with the way the site saves the files recently? Or is this just a farm foundry issue? And if you did by chance change anything would it be possible to add which save format is used when saving? So if I put in a PS4 save I can then save it as a PC save? When I first started using the site it used to auto name my file "todo" when saving the edited file, and that file would also work with Farm Foundry! Then it actually started keeping its file name it started with and I'd just replace the existing one on my desktop with the new one and that would also work. But today it didn't and I've tried like 10 times. Thank you again sorry for the very long txt. Just wanted to be as detailed as possible!

**Comment by colecrouter** [comment]
Hi, there have been quite a few changes recently, but none that *should* affect save formats (over the last couple weeks, at least).

It's possible that your save progressed in a certain way, and that FF isn't handling it properly. For reference, I tried what the same thing with a new PC save, and I didn't see any issues in FF. I'm not aware of any differences between PS4 and PC save formats either, so it could just be an issue with FF.

What happens when you open the save in FF? (is there a message?) Does the save still work on your PS4 after uploading it back?

**Comment by SirTribby** [comment]
So after further investigation. The site just is not working with my save in general anymore. I decided I'd just do multiple trips to the editor to get all the items i wanted in my bag and call it a day! However, My save wont load anymore (I had back ups obviously so all good there) but the modded save just immediately crashes upon loading it. The save still loads into the website just fine, Save Wizard still accepts the file when I copy the Notepad contents of the save and then delete my data on my save and paste in what i copied. All works until I load the file in game and just boom crash. Where as I know I was able to use this just fine beforehand and I never crashed. Maybe my save did progress in a weird way? But I'm so lost on how that even makes sense of why it would crash now, but not like 2 weeks ago. Cause I've also looked at a pc save and its formatted the same for sure so it's just confusing as all can be!

**Comment by colecrouter** [comment]
It sure can be confusing, that's for sure.

Would you be willing to share any or all of those files here? If it's crashing in-game, it's likely an issue on my end. I might be able to get some insight into the FF issue as well.

If you have them on your computer, you can just ZIP them and upload them here directly.

**Comment by SirTribby** [comment]
[Stardew Valley saves.zip](https://github.com/user-attachments/files/17929486/Stardew.Valley.saves.zip)
Hopefully I did that right! I wrote a read me in the file!

**Comment by SirTribby** [comment]
I would be curious to know if the save that crashes, crashes on PC as well? if it doesn't then well I'd just be confused even more. But if it does crash maybe there's something there we can pinpoint.

**Comment by colecrouter** [comment]
Thanks! I was able to pin it down to a couple issues with some new(-er) furniture and hats, which should (hopefully) be fixed now.

As for the PS4 save, I did notice something very interesting. In your "before" save, at the bottom there's this:
```xml
<compressed>
```
and in the "after" save, there's this:
```xml
<compressed />
```

I'm not sure if this is left over from Save Wizard, or if this is actually part of the PS4 save file format. This isn't actually valid XML. Because of that:
- On PC, neither version runs until the offending `<compressed>` tag is removed.
- This is probably what was causing FF to crash.
- This editor ignores all invalid XML and only spits out the main XML structure.
  - That might be why you could edit the save in FF *after* exporting it from this site.

[I was able to get your "bad" save working on PC.](https://github.com/user-attachments/files/17938357/Collins_390424511.zip) Let me know how it looks on your end.

**Comment by SirTribby** [comment]
So I just exported my save fresh and raw to test just to see if that tag is there and it 100% is, So that <compressed> is just default for ps4 saves it seems. Might literally be the only difference between the platforms saves honestly. So after taking out the whole <compressed> line it 100% loads on FF no issues, wild. Hate when things are that simple! Unfortunately it wasn't that simple, as the save still crashes upon loading in game, am gonna try a few more things though and will update this, Alright so after putting my save back in the editor I removed the hats and added them back cause I know you mentioned something wrong with them that you just fixed! I saved, then for extra measure I then put my save into FF and  saved with formatting, (I used to just save without formatting and it'd work but considering the circumstances I figured id give the formatting a try lol) and to my surprise I am on my save as we speak no crashes whatsoever all items there no issues at all! I'm going to put all these items in a chest and then do all the steps over and try just removing the <compressed> tag and just using your editor alone and make sure its working as intended and for future ps4 users you may encounter with similar issues I faced! YOU ARE THE MAN, Thank you for helping so much I'm glad we were able to get to the bottom of it and figuring out the issues! And hopefully this can help people in the future as well! I'm gonna write a tutorial out just in case you wanna put it on the site somewhere for future reference or in case somebody finds this later! Unfortunately that whole <compressed> line has to be deleted for it to work no matter what. The site accepts it but even if you get rid of the space and the / it creates it still crashes upon loading the save, so just getting rid of the whole line is what has to be done. Very odd but usually stuff like this is odd lol! And the hats and catalogs I was trying to add could have also been of some cause but regardless the method below works flawlessly and I see this as a a win! 
-Console Tutorial *Save Wizard required, it is a $60 program that can decrypt PS4 saves*
Put save on USB and head to Save Wizard
Open the save in Advanced mode by right clicking the save and selecting "Advanced mode"
In the top right hit export to file and export the file 
Right click the file you exported and hit open with and choose notepad (I'm sure there are other notepad applications that could be used here this is just what I have on my computer.)
Go to edit and hit find and type in "compressed" without the quotes.
delete this whole line <compressed>
save the file and close notepad and then drag and drop the file into the save editor
edit what you want than save the file as a new file or replace the existing one you have already either or. 
open it back up in notepad by right clicking and open with again. 
CTL+A to select all the txt and then CTL+C to copy everything
Advanced mode should still be open if not re open advanced mode for the save and CTA+A again but this time delete everything
CTL+V to paste in what you copied from the notepad 
Save Load back up and you have officially modded Stardew on PS4 <3

**Comment by colecrouter** [comment]
Great follow up. I'll add some of this info here/on the website. Hopefully that will help people out going forward.

**Comment by CostelaCNX** [comment]
thank you for you both for the research! Works fine!!!! I use a nexus mod editor too, have a little more functions maybe you can add to your program too @colecrouter. THANK YOU SO MUCH AGAIN !
