### ISSUE TITLE
Save doesn't load

### ISSUE THREAD

**Issue by Noacy** [colecrouter/stardew-save-editor#41]
**Describe the bug**
When I load my save nothing happen on the save editor. One week ago, I already used the save editor on a previous version of my save and everything was working/loading well. 
I try to sleep to get new save files but it's not loading. With the copy of my old save it still work/loading well

**Save file**
[Saves.zip](https://github.com/user-attachments/files/18008446/Saves.zip)
Here my working save (old_Lartigue_39...) and my curent not working (Lartigue_39...)

**Device info**
 - OS:  android
 - Browser: chrome, Firefox
 - Version: Last version of Stardew

**Additional context**
One week ago, I already used the save editor on a previous version of my save and everything was working/loading well. 
I try to sleep in game to get new save files but it's not loading. With the copy of my old save it still work/loading well

**Comment by colecrouter** [comment]
Thanks for the report. It should be fixed now. Let me know if you have further issues.

**Comment by duduws** [comment]
"Uncaught Error: Invalid sprite index
    at T.getSprite (save.svelte.j8NDszts.js:1:616910)
    at new T (save.svelte.j8NDszts.js:1:616341)
    at new G (save.svelte.j8NDszts.js:1:618299)
    at Ie.getItem (save.svelte.j8NDszts.js:1:625273)
    at get hat (save.svelte.j8NDszts.js:1:625864)
    at get hat (save.svelte.j8NDszts.js:1:632111)
    at Character.C-C6sJQK.js:1:6974
    at Vt (runtime.jI9HaXbs.js:1:7843)
    at Ot (runtime.jI9HaXbs.js:1:3749)
    at xt (runtime.jI9HaXbs.js:1:3798)
    
    "
    
    Getting this error in console, trying to upload the save and it wont show anything in the screen, just the background image.
