### ISSUE TITLE
File Upload Fails and Wont Display Anything in Browser - Error

### ISSUE THREAD

**Issue by duduws** [colecrouter/stardew-save-editor#42]
**Describe the bug**
Attempting to upload a save file does not work; the screen displays only the background of the website.

In the browser console (using Brave on Windows 11, also tested on Edge with the same result), the following error is displayed:
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
Additionally, the following runtime error is logged:

```
runtime.jI9HaXbs.js:1 Uncaught Error: Invalid sprite index
    at T.getSprite (save.svelte.j8NDszts.js:1:616910)
    at new T (save.svelte.j8NDszts.js:1:616341)
    ...
```

**To Reproduce**

Open the application.
Navigate to the save file upload section.
Attempt to upload a save file.

**Expected behavior**
The save file should load, and the website should display the saved data.

**Screenshots**
![image](https://github.com/user-attachments/assets/5a709316-1e3b-4d15-8b46-f63167ccee2d)

**Save file**

[Esperanza_392256856.zip](https://github.com/user-attachments/files/18024548/Esperanza_392256856.zip)

**Device info**
 - OS: Windows 11
 - Browser Brave, Edge (tested on both)
 - Version Latest versions of Brave and Edge at the time of testing

**Additional context**
The issue occurs consistently across multiple browsers. A permissions policy error is logged (Unrecognized feature: 'interest-cohort'), followed by a runtime error regarding an invalid sprite index in the JavaScript file.

**Comment by colecrouter** [comment]
Thanks for the report. It looks the dump format for hat items wasn't correct. I'm currently in the process of refactoring lots of that code. You should be good to go now 👍
