### ISSUE TITLE
(iOS) Game reverts to older save

### ISSUE THREAD

**Issue by carter0nline** [colecrouter/stardew-save-editor#45]
When I try to load a modified save, the game pulls one from the previous (ingame) day or so out of its ass instead of loading the one I just modified. I’m on iOS 18.1.1, Stardew Valley v1.6.14.11 build 24341. Turning off iCloud for Stardew in the settings app didn’t change anything.

This is what my save folder looks like. Could it have something to do with the SVBAK or SVEMERG files?
![IMG_0443](https://github.com/user-attachments/assets/46e6ca0f-dcf0-4dbf-8e70-1a11912a0ce1)

**Comment by colecrouter** [comment]
The weird backup files are normal, although I'm not sure under what circumstances they're created. I have the same files on my Android save; I think those are just copies for if the app crashes.

Would you be willing to upload a copy of these two files?
![image](https://github.com/user-attachments/assets/a3304818-0591-439e-9d17-196dbe698823)
It's not impossible that there's an iOS-specific format issue, or maybe it's an issue I can recreate on PC.

**Comment by carter0nline** [comment]
Since iOS doesn’t like XML files, I used an online tool to check out the files, and found they use different encoding! I think this could be the problem?
![IMG_0450](https://github.com/user-attachments/assets/4961bff8-f1ad-44
![IMG_0451](https://github.com/user-attachments/assets/f39651e4-a52a-45fb-b335-0c18184059d9)
af-b6c3-dcada2a80ae7)

**Comment by arkbriar** [comment]
Same issue here. I did several experiments and found that:
- Encoding needs to be changed to UTF8-BOM
- Some quotes `&quot;` need to be replaced with `"`
- Some items will cause loading failure, such as "Advanced Iridium Rod` (skill doesn't match), `Iridium Trash Bin`, `Infinity blade` and so on.

Hope that helps.

**Comment by colecrouter** [comment]
Huge thanks for the research, both of you @carter0nline @arkbriar. I've pushed a patch to force UTF-8 BOM encoding when exporting. Hopefully that fixes the issue. It would be awesome if you could try it out for me, and let me know if it's working. There's a [test save file](https://github.com/colecrouter/stardew-save-editor/blob/main/test/TestSave) you can use, if you wish.

@arkbriar thanks again, would you mind elaborating on your last point? My knowledge is a bit outdated as far SDV goes 😅

**Comment by arkbriar** [comment]
> @arkbriar thanks again, would you mind elaborating on your last point? My knowledge is a bit outdated as far SDV goes 😅

😄 sure. The thing is, I successfully edited my save with the editor after applying the first two points. I've 
- Changed the current funding
- Added a set of iridium farming tools, such as the [Iridium Axe](https://stardewvalleywiki.com/Iridium_Axe) and the [Iridium Hoe](https://stardewvalleywiki.com/Hoes)

The iOS/iPadOS version supports the backup save for players to save during a day, and the file saved has a suffix of `_SVBAK` (like what's in the pic above). When the backup save is newer than the daily save, the game will ask if I want to use it. So I edited and overrode the backup save to avoid the fallback loading issue here.

However, when some items were added in the character's bag, e.g., the [Advanced Iridium Rod](https://stardewvalleywiki.com/Advanced_Iridium_Rod), the game refused to load the save and returned to title. I've tried several ones and here's the list that will break my save:
- [Advanced Iridium Rod](https://stardewvalleywiki.com/Advanced_Iridium_Rod)
- Infinity weapons, such as the [Infinity Blade](https://stardewvalleywiki.com/Infinity_Blade)
- [Iridium Trash Can](https://stardewvalleywiki.com/File:Trash_Can_Iridium.png)

My suspect is the character's skill or progress doesn't match the items so the edited save is determined malformed.

**Comment by carter0nline** [comment]
Did a little more testing.
The encoding is right now, but if I make certain changes Stardew will just go back to the title screen when I try to load the modified file.
So far I’ve been able to change my name, going to try some other stuff.

Also I was able to delete the “old” “svbak” snd “svemerg” files with no issues.

**Comment by carter0nline** [comment]
Okay, I was able to change relationships just fine, as well as adding 1 amethyst to my inventory.
However trying to add a tank top will cause it to go back to the title screen. I think it could have something to do with having spaces in the name of the item?

**Comment by colecrouter** [comment]
Both issues should be somewhat fixed now.

- I wasn't able to recreate @arkbriar's issue with the Infinity Blade, unfortunately. Maybe more research is required.
- I'm not sure what to do about the Trash Cans at the moment; I don't think they're technically "real" items.

**Comment by colecrouter** [comment]
I've concluded that the remaining issues aren't relevant/exclusive to iOS/mobile, so I'm going to close this thread for now.

I'll keep the above info in mind for the future, thanks.
