### ISSUE TITLE
Not compatible with 1.6.3

### ISSUE THREAD

**Issue by stardewgirly** [colecrouter/stardew-save-editor#5]
Are there plans to update save editor for version 1.6.3? I had a glitch that I need to edit or else I won't be able to get completion at the end of the game

**Comment by colecrouter** [comment]
Thanks for opening an issue. I plan on updating it, hopefully within the next couple weeks. The underlying game data has changes drastically. I'm torn between two options:
- Taking the time to try to support 1.5 & 1.6
- Dropping 1.5 support

While I don't like the idea of removing functionality for current console/mobile players, either:
- Maintaining two versions of the editor
- Finding a way to integrate both versions' data formats

—both will take more time than I can offer.

Maybe I'll drop 1.5 for now, and later find a way to publish two versions of the site; one for 1.5 (current version), and one for 1.6+.

**Comment by stardewgirly** [comment]
I appreciate the thought you're putting into this! I am very happy to wait longer for you to take your time to find out how to support both versions at once. The issue I'm having with my game is I forgot to collect my ancient seed recipe from the museum and when I went back to try and do so it was no longer there, meaning now I can never reach completion in the game without that recipe. I have heard the only way to get there with this glitch is to edit your save file. But this is no rush! A question I have is I play this game through steam on a Mac--is this save editor compatible with Macs?

**Comment by colecrouter** [comment]
Thanks for the kind response. Luckily, SDV uses the same save file format across all platforms except Nintendo Switch, so this editor is compatible with all other platforms. Other editors exist, such as [Farm Foundry](https://www.nexusmods.com/stardewvalley/mods/127/) which got 1.6 support yesterday, but the program itself only _runs_ on Windows.

Rest assured, you'll be able to get your Ancient Seed recipe.

**Comment by Trenjeska** [comment]
Same reason I came here. I got the seed packet, but not the recipe.
I tried loading the save into the standard text editor (gedit; pop_os 22.04), but it cannot handle the size.
On windows I would have used notepad++, but not on windows anymore.
...Sorry to ask, but could you recommend any light weight (graphical, not vi(m)/nano) text editor that will easily handle megabyte sized text documents?

**Comment by colecrouter** [comment]
> Same reason I came here. I got the seed packet, but not the recipe. I tried loading the save into the standard text editor (gedit; pop_os 22.04), but it cannot handle the size. On windows I would have used notepad++, but not on windows anymore. ...Sorry to ask, but could you recommend any light weight (graphical, not vi(m)/nano) text editor that will easily handle megabyte sized text documents?

Honestly, I've just been using VSCode. So much for "lightweight" but it works.

**Comment by colecrouter** [comment]
Alright, it should be finished enough for basic usage. Post back here if you have any issues unlocking crafting recipes. If anyone else has _other_ issues with the update, please open another issue so I can keep track of it separately.

~Always keep a backup of your save file

**Comment by stardewgirly** [comment]
Hi there! I'm trying it out now and to be fair I have never done this before and I could totally be doing something wrong. But, put my game into the save editor and I checked off the ancient seed. However, when I save it to my folder that my game's save files are in and then I go on steam to play, it's not registering my game as like... a file that can be played? So I have a saves folder that all my past stardew save files are in and when my current save file is in there with just the game that has been saved from the save editor in there, on stardew it doesn't register this save file. Not sure what the fix to this is or if you know what I'm doing wrong!

**Comment by stardewgirly** [comment]
OKAY I have no clue what I did but it works now!!!!
